[[assets]]
name = "USD Coin"
ticker = "USDC"
decimals = 6
ethereum_address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
starknet_address = "0x033068F6539f8e6e6b131e6B2B814e6c34A5224bC66947c47DaB9dFeE93b35fb"

[[assets]]
name = "USDC.e Bridged"
ticker = "USDC.E"
decimals = 6
ethereum_address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
starknet_address = "0x053C91253BC9682c04929cA02ED00b3E423f6710D2ee7e0D5EBB06F3eCF368A8"

[[assets]]
name = "Tether USD"
ticker = "USDT"
decimals = 6
address = "0x068F5c6a61780768455de69077E07e89787839bf8166dEcfBf92B645209c0fB8"

[[assets]]
name = "Starknet"
ticker = "STRK"
decimals = 18
address = "0x4718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d"

[[assets]]
name = "Endur xSTRK"
ticker = "xSTRK"
decimals = 18
address = "0x028d709c875c0ceac3dce7065bec5328186dc89fe254527084d1689910954b0a"

[[assets]]
name = "Ethereum"
ticker = "ETH"
decimals = 18
address = "0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"

[[assets]]
name = "Starknet Wrapped Staked Ether"
ticker = "wstETH"
decimals = 18
address = "0x0057912720381af14b0e5c87aa4718ed5e527eab60b3801ebf702ab09139e38b"

[[assets]]
name = "Wrapped BTC"
ticker = "WBTC"
decimals = 8
address = "0x03Fe2b97C1Fd336E750087D68B9b867997Fd64a2661fF3ca5A7C771641e8e7AC"

[[assets]]
name = "Starknet tBTC"
ticker = "tBTC"
decimals = 18
address = "0x04daa17763b286d1e59b97c283c0b8c949994c361e426a28f743c67bdfe9a32f"

[[assets]]
name = "uniBTC"
ticker = "uniBTC"
decimals = 8
address = "0x023a312ece4a275e38c9fc169e3be7b5613a0cb55fe1bece4422b09a88434573"

[[assets]]
name = "Solv BTC"
ticker = "solvBTC"
decimals = 18
address = "0x0593e034dda23eea82d2ba9a30960ed42cf4a01502cc2351dc9b9881f9931a68"

[[assets]]
name = "Lombard Staked Bitcoin"
ticker = "LBTC"
decimals = 8
address = "0x036834a40984312f7f7de8d31e3f6305b325389eaeea5b1c0664b2fb936461a4"

[[assets]]
name = "Endur xsBTC"
ticker = "xsBTC"
decimals = 18
address = "0x0580f3dc564a7b82f21d40d404b3842d490ae7205e6ac07b1b7af2b4a5183dc9"

[[assets]]
name = "Endur xWBTC"
ticker = "xWBTC"
decimals = 8
address = "0x06a567e68c805323525fe1649adb80b03cddf92c23d2629a6779f54192dffc13"

[[assets]]
name = "Endur xtBTC"
ticker = "xtBTC"
decimals = 18
address = "0x043a35c1425a0125ef8c171f1a75c6f31ef8648edcc8324b55ce1917db3f9b91"

[[assets]]
name = "Midas Re7 BTC"
ticker = "mRe7BTC"
decimals = 18
address = "0x04e4fb1a9ca7e84bae609b9dc0078ad7719e49187ae7e425bb47d131710eddac"

[[assets]]
name = "Endur xLBTC"
ticker = "xLBTC"
decimals = 8
address = "0x07dd3c80de9fcc5545f0cb83678826819c79619ed7992cc06ff81fc67cd2efe0"

[[assets]]
name = "Yield BTC.B"
ticker = "YBTC.B"
decimals = 8
address = "0x02cab84694e1be6af2ce65b1ae28a76009e8ec99ec4bc17047386abf20cbb688"

[[assets]]
name = "Midas Re7 Yield"
ticker = "mRe7YIELD"
decimals = 18
address = "0x04be8945e61dc3e19ebadd1579a6bd53b262f51ba89e6f8b0c4bc9a7e3c633fc"

[[assets]]
name = "USN"
ticker = "USN"
decimals = 18
address = "0x01e6545cab7ba4ac866768ba5e1bd540893762286ed3fea7f9c02bfa147e135b"

[[assets]]
name = "Staked USN"
ticker = "sUSN"
decimals = 18
address = "0x02411565ef1a14decfbe83d2e987cced918cd752508a3d9c55deb67148d14d17"
